In [1]:
import pandas as pd

In [2]:
health_risks_df = pd.read_csv("../data/raw/Health_Risk_factors.csv")
health_risks_df.head()

,Country,Prevalence of smoking Male % of adults 2016,Prevalence of smoking female % of adults 2016,"Incidence of tuberculosis per 100,000 people 2018",Prevalence of diabetes % of population ages 20 to 79 2019,"Incidence of HIV Total per 1,000 uninfected population ages 15-49 2018",Prevalence of HIV Total % of population ages 15-49 2018,Prevalence of HIV Women's share of population ages 15+ living with HIV % 2018,"Prevalence of HIV Youth, Male % of population ages 15-24 2018","Prevalence of HIV Youth, Female % of population ages 15-24 2018",Antiretroviral therapy coverage % of people living with HIV 2018,"Cause of death Communicable diseases and maternal, prenatal, and nutrition conditions % of population 2016",Cause of death Non-communicable diseases % of population 2016,Cause of death Injuries % of population 2016
0,Afghanistan,NaN,NaN,189.0,9.2,0.04,0.1,29.0,0.1,0.1,13.0,36.0,44.0,20.0
1,Albania,51.0,7.0,18.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,3.0,93.0,4.0
2,Algeria,30.0,1.0,69.0,6.7,0.05,0.1,46.0,0.1,0.1,81.0,15.0,76.0,10.0
3,American Samoa,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,38.0,29.0,3.0,7.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
health_system_df = pd.read_csv("../data/raw/health_system.csv")
health_system_df.head()

,Country,Health expenditure Current % of GDP 2016,Health expenditure Public % of current 2016,Health expenditure Out of pocket % of current 2016,Health expenditure per capita $ 2016,Health expenditure per capita current PPP $ 2016,External health expenditure (% of current health expenditure) 2016,"Health workers Physicians per 1,000 people 2009-18","Health workers Nurses and midwives per 1,000 people 2009-18","Specialist surgical workforce per 100,000 population 2008-18",Completeness of birth registration % 2009-18,Completeness of death registration % 2008-16
0,Afghanistan,10.2,5.1,77.4,57.2,162.8,17.5,0.3,0.3,0.0,42.3,NaN
1,Albania,6.7,41.4,58.0,271.5,759.7,0.7,1.2,3.6,11.6,98.4,53.0
2,Algeria,6.6,67.7,30.9,260.4,998.2,0.0,1.8,2.2,12.1,100.0,NaN
3,American Samoa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,10.4,49.1,41.7,NaN,NaN,NaN,3.3,4.0,83.1,100.0,80.0

In [4]:
ghg_emission_df = pd.read_csv("../data/raw/greenhouse_gas_emissions.csv")
ghg_emission_df.head()

,Country,Total greenhouse gas emissions thousand metric tons of carbon dioxide equivalent 2012,Total greenhouse gas emissions % change 1990-2012,Methane emissions thousand metric tons of carbon dioxide equivalent 2012,Methane emissions % change 1990-2012,Methane emissions From energy processes % of total 2008,Methane emissions Agricultural % of total 2008,Nitrous oxide emissions thousand metric tons of carbon dioxide equivalent 2012,Nitrous oxide emissions % change 1990-2012,Nitrous oxide emissions From energy processes % of total 2008,Nitrous oxide emissions Agricultural % of total 2008,Other greenhouse gas emissions thousand metric tons of carbon dioxide equivalent 2012,Other greenhouse gas emissions % change 1990-2012
0,Afghanistan,NaN,43.5,NaN,80.4,8.2,62.7,NaN,24.6,6.0,71.3,NaN,118.1
1,Albania,NaN,-19.9,NaN,3.8,25.8,65.0,NaN,-26.5,6.2,80.6,900.0,-75.0
2,Algeria,NaN,65.8,NaN,50.2,79.4,10.0,NaN,49.9,7.2,53.9,NaN,202.7
3,American Samoa,58.8,188.3,13.0,48.3,0.0,24.8,24.0,NaN,0.0,99.2,0.0,433.3
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,NaN,NaN

In [5]:
health_risks_df.describe()

,Prevalence of smoking Male % of adults 2016,Prevalence of smoking female % of adults 2016,"Incidence of tuberculosis per 100,000 people 2018",Prevalence of diabetes % of population ages 20 to 79 2019,"Incidence of HIV Total per 1,000 uninfected population ages 15-49 2018",Prevalence of HIV Total % of population ages 15-49 2018,Prevalence of HIV Women's share of population ages 15+ living with HIV % 2018,"Prevalence of HIV Youth, Male % of population ages 15-24 2018","Prevalence of HIV Youth, Female % of population ages 15-24 2018",Antiretroviral therapy coverage % of people living with HIV 2018,"Cause of death Communicable diseases and maternal, prenatal, and nutrition conditions % of population 2016",Cause of death Non-communicable diseases % of population 2016,Cause of death Injuries % of population 2016
count,143.000000,145.000000,207.000000,208.000000,137.000000,141.000000,139.000000,137.000000,137.000000,139.000000,183.000000,183.000000,183.000000
mean,32.923077,10.620690,102.893720,8.293269,1.004307,1.837589,39.330935,0.442336,0.893431,56.093525,22.316940,68.781421,9.049180
std,13.678438,10.528446,137.634271,4.730419,2.294370,4.309152,17.419957,0.817701,2.230280,20.251997,20.291504,21.922598,5.017857
min,8.000000,0.000000,0.000000,1.000000,0.010000,0.100000,6.000000,0.100000,0.100000,9.000000,1.000000,24.000000,3.000000
25%,22.500000,2.000000,9.500000,5.250000,0.100000,0.100000,28.000000,0.100000,0.100000,42.000000,6.000000,48.500000,6.000000
50%,31.000000,6.000000,45.000000,6.850000,0.200000,0.400000,36.000000,0.100000,0.100000,56.000000,13.000000,75.000000,9.000000
75%,41.500000,19.000000,144.000000,10.400000,0.800000,1.400000,58.500000,0.400000,0.600000,72.000000,36.000000,87.000000,11.000000
max,78.000000,44.000000,611.000000,30.500000,15.400000,27.300000,72.000000,4.900000,15.900000,92.000000,65.000000,95.000000,50.000000

In [6]:
health_risks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 14 columns):
 #   Column                                                                                                      Non-Null Count  Dtype
---  ------                                                                                                      --------------  -----
 0   Country                                                                                                     214 non-null    object
 1   Prevalence of smoking Male % of adults 2016                                                                 143 non-null    float64
 2   Prevalence of smoking female % of adults 2016                                                               145 non-null    float64
 3   Incidence of tuberculosis  per 100,000 people 2018                                                          207 non-null    float64
 4   Prevalence of diabetes  % of population ages 20 to 79 2019                                                  208 non-null    float64
 5   Incidence of HIV Total per 1,000 uninfected population ages 15-49 2018                                      137 non-null    float64
 6   Prevalence of HIV Total % of population ages 15-49 2018                                                     141 non-null    float64
 7   Prevalence of HIV Women's share of population ages 15+ living with HIV % 2018                               139 non-null    float64
 8   Prevalence of HIV Youth, Male % of population ages 15-24 2018                                               137 non-null    float64
 9   Prevalence of HIV Youth, Female % of population ages 15-24 2018                                             137 non-null    float64
 10  Antiretroviral therapy coverage  % of people living with HIV 2018                                           139 non-null    float64
 11  Cause of death Communicable diseases and maternal, prenatal, and nutrition conditions % of population 2016  183 non-null    float64
 12  Cause of death Non-communicable diseases % of population 2016                                               183 non-null    float64
 13  Cause of death Injuries % of population 2016                                                                183 non-null    float64
dtypes: float64(13), object(1)
memory usage: 23.5+ KB

In [7]:
health_risks_df.columns

Index(['Country', 'Prevalence of smoking Male % of adults 2016',
       'Prevalence of smoking female % of adults 2016',
       'Incidence of tuberculosis  per 100,000 people 2018',
       'Prevalence of diabetes  % of population ages 20 to 79 2019',
       'Incidence of HIV Total per 1,000 uninfected population ages 15-49 2018',
       'Prevalence of HIV Total % of population ages 15-49 2018',
       'Prevalence of HIV Women's share of population ages 15+ living with HIV % 2018',
       'Prevalence of HIV Youth, Male % of population ages 15-24 2018',
       'Prevalence of HIV Youth, Female % of population ages 15-24 2018',
       'Antiretroviral therapy coverage  % of people living with HIV 2018',
       'Cause of death Communicable diseases and maternal, prenatal, and nutrition conditions % of population 2016',
       'Cause of death Non-communicable diseases % of population 2016',
       'Cause of death Injuries % of population 2016'],
      dtype='object')

In [16]:
nan_counts = health_risks_df.isna().sum()
print(nan_counts)

Country                                                                                                        0
Prevalence of smoking Male % of adults 2016                                                                   71
Prevalence of smoking female % of adults 2016                                                                 69
Incidence of tuberculosis  per 100,000 people 2018                                                             7
Prevalence of diabetes  % of population ages 20 to 79 2019                                                     6
Incidence of HIV Total per 1,000 uninfected population ages 15-49 2018                                        77
Prevalence of HIV Total % of population ages 15-49 2018                                                       73
Prevalence of HIV Women's share of population ages 15+ living with HIV % 2018                                 75
Prevalence of HIV Youth, Male % of population ages 15-24 2018                                                 77
Prevalence of HIV Youth, Female % of population ages 15-24 2018                                               77
Antiretroviral therapy coverage  % of people living with HIV 2018                                             75
Cause of death Communicable diseases and maternal, prenatal, and nutrition conditions % of population 2016    31
Cause of death Non-communicable diseases % of population 2016                                                 31
Cause of death Injuries % of population 2016                                                                  31
dtype: int64

In [8]:
health_system_df.describe()

,Health expenditure Current % of GDP 2016,Health expenditure Public % of current 2016,Health expenditure Out of pocket % of current 2016,Health expenditure per capita $ 2016,Health expenditure per capita current PPP $ 2016,External health expenditure (% of current health expenditure) 2016,"Health workers Physicians per 1,000 people 2009-18","Health workers Nurses and midwives per 1,000 people 2009-18","Specialist surgical workforce per 100,000 population 2008-18",Completeness of birth registration % 2009-18,Completeness of death registration % 2008-16
count,186.000000,186.000000,186.000000,136.000000,110.000000,167.000000,189.000000,189.000000,175.000000,163.000000,107.000000
mean,6.715054,52.915054,32.661828,262.872059,386.331818,9.116766,1.723280,4.139153,37.937143,84.202454,89.309346
std,2.976537,21.957736,19.572777,251.132803,293.827202,13.868251,1.570366,3.965282,40.877520,23.370024,18.071157
min,1.700000,5.100000,0.100000,16.400000,29.900000,0.000000,0.000000,0.100000,0.000000,2.700000,4.000000
25%,4.500000,36.825000,16.200000,64.050000,131.075000,0.200000,0.300000,1.100000,3.100000,77.150000,85.500000
50%,6.200000,55.850000,30.100000,183.950000,295.500000,1.700000,1.300000,2.800000,23.600000,96.000000,99.000000
75%,8.375000,70.600000,44.825000,399.425000,574.425000,13.400000,2.800000,6.100000,62.150000,100.000000,100.000000
max,23.300000,96.000000,81.000000,987.900000,998.200000,69.200000,8.200000,20.300000,195.600000,100.000000,100.000000

In [9]:
health_system_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 12 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Country                                                               214 non-null    object
 1   Health expenditure Current % of GDP 2016                              186 non-null    float64
 2   Health expenditure Public % of current 2016                           186 non-null    float64
 3   Health expenditure Out of pocket % of current 2016                    186 non-null    float64
 4   Health expenditure per capita $ 2016                                  136 non-null    float64
 5   Health expenditure per capita current PPP $ 2016                      110 non-null    float64
 6   External health expenditure (% of current health expenditure)   2016  167 non-null    float64
 7   Health workers Physicians per 1,000 people 2009-18                    189 non-null    float64
 8   Health workers Nurses and midwives per 1,000 people 2009-18           189 non-null    float64
 9   Specialist surgical workforce  per 100,000 population 2008-18         175 non-null    float64
 10  Completeness of birth registration  % 2009-18                         163 non-null    float64
 11  Completeness of death registration  % 2008-16                         107 non-null    float64
dtypes: float64(11), object(1)
memory usage: 20.2+ KB

In [10]:
health_system_df.columns

Index(['Country', 'Health expenditure Current % of GDP 2016',
       'Health expenditure Public % of current 2016',
       'Health expenditure Out of pocket % of current 2016',
       'Health expenditure per capita $ 2016',
       'Health expenditure per capita current PPP $ 2016',
       'External health expenditure (% of current health expenditure)   2016',
       'Health workers Physicians per 1,000 people 2009-18',
       'Health workers Nurses and midwives per 1,000 people 2009-18',
       'Specialist surgical workforce  per 100,000 population 2008-18',
       'Completeness of birth registration  % 2009-18',
       'Completeness of death registration  % 2008-16'],
      dtype='object')

In [15]:
nan_counts = health_system_df.isna().sum()
print(nan_counts)

Country                                                                   0
Health expenditure Current % of GDP 2016                                 28
Health expenditure Public % of current 2016                              28
Health expenditure Out of pocket % of current 2016                       28
Health expenditure per capita $ 2016                                     78
Health expenditure per capita current PPP $ 2016                        104
External health expenditure (% of current health expenditure)   2016     47
Health workers Physicians per 1,000 people 2009-18                       25
Health workers Nurses and midwives per 1,000 people 2009-18              25
Specialist surgical workforce  per 100,000 population 2008-18            39
Completeness of birth registration  % 2009-18                            51
Completeness of death registration  % 2008-16                           107
dtype: int64

In [11]:
ghg_emission_df.describe()

,Total greenhouse gas emissions thousand metric tons of carbon dioxide equivalent 2012,Total greenhouse gas emissions % change 1990-2012,Methane emissions thousand metric tons of carbon dioxide equivalent 2012,Methane emissions % change 1990-2012,Methane emissions From energy processes % of total 2008,Methane emissions Agricultural % of total 2008,Nitrous oxide emissions thousand metric tons of carbon dioxide equivalent 2012,Nitrous oxide emissions % change 1990-2012,Nitrous oxide emissions From energy processes % of total 2008,Nitrous oxide emissions Agricultural % of total 2008,Other greenhouse gas emissions thousand metric tons of carbon dioxide equivalent 2012,Other greenhouse gas emissions % change 1990-2012
count,18.000000,186.000000,45.000000,200.000000,201.000000,201.000000,69.000000,201.000000,202.000000,202.000000,47.00000,161.000000
mean,381.300000,71.663978,152.666667,37.144500,25.910945,42.623881,221.652174,25.647761,8.986139,63.426238,109.12766,80.692547
std,306.474031,128.079877,211.722911,79.603798,24.831294,26.055390,266.024370,81.476506,9.038338,25.248245,462.17739,258.777001
min,5.200000,-78.000000,0.000000,-100.000000,0.000000,0.000000,0.000000,-100.000000,0.000000,0.000000,-883.00000,-620.000000
25%,103.250000,-7.525000,29.000000,2.025000,6.800000,21.900000,15.000000,-25.400000,3.200000,51.950000,-72.00000,-86.900000
50%,337.650000,42.750000,46.000000,24.100000,16.700000,42.100000,81.000000,14.800000,6.500000,69.300000,55.00000,-3.600000
75%,590.150000,112.100000,215.000000,60.850000,40.100000,64.600000,344.000000,49.900000,12.100000,82.375000,357.00000,168.100000
max,959.300000,828.900000,732.000000,834.700000,97.600000,96.800000,990.000000,648.200000,60.700000,99.300000,988.00000,983.400000

In [12]:
ghg_emission_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 13 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Country                                                                                 214 non-null    object
 1   Total greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012  18 non-null     float64
 2   Total greenhouse gas emissions  % change 1990-2012                                      186 non-null    float64
 3   Methane emissions  thousand metric tons of carbon dioxide equivalent 2012               45 non-null     float64
 4   Methane emissions  % change 1990-2012                                                   200 non-null    float64
 5   Methane emissions From energy processes % of total 2008                                 201 non-null    float64
 6   Methane emissions Agricultural % of total 2008                                          201 non-null    float64
 7   Nitrous oxide emissions  thousand metric tons of carbon dioxide equivalent 2012         69 non-null     float64
 8   Nitrous oxide emissions  % change 1990-2012                                             201 non-null    float64
 9   Nitrous oxide emissions From energy processes % of total 2008                           202 non-null    float64
 10  Nitrous oxide emissions Agricultural % of total 2008                                    202 non-null    float64
 11  Other greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012  47 non-null     float64
 12  Other greenhouse gas emissions  % change 1990-2012                                      161 non-null    float64
dtypes: float64(12), object(1)
memory usage: 21.9+ KB

In [13]:
ghg_emission_df.columns

Index(['Country',
       'Total greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012',
       'Total greenhouse gas emissions  % change 1990-2012',
       'Methane emissions  thousand metric tons of carbon dioxide equivalent 2012',
       'Methane emissions  % change 1990-2012',
       'Methane emissions From energy processes % of total 2008',
       'Methane emissions Agricultural % of total 2008',
       'Nitrous oxide emissions  thousand metric tons of carbon dioxide equivalent 2012',
       'Nitrous oxide emissions  % change 1990-2012',
       'Nitrous oxide emissions From energy processes % of total 2008',
       'Nitrous oxide emissions Agricultural % of total 2008',
       'Other greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012',
       'Other greenhouse gas emissions  % change 1990-2012'],
      dtype='object')

In [14]:
nan_counts = ghg_emission_df.isna().sum()
print(nan_counts)

Country                                                                                     0
Total greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012    196
Total greenhouse gas emissions  % change 1990-2012                                         28
Methane emissions  thousand metric tons of carbon dioxide equivalent 2012                 169
Methane emissions  % change 1990-2012                                                      14
Methane emissions From energy processes % of total 2008                                    13
Methane emissions Agricultural % of total 2008                                             13
Nitrous oxide emissions  thousand metric tons of carbon dioxide equivalent 2012           145
Nitrous oxide emissions  % change 1990-2012                                                13
Nitrous oxide emissions From energy processes % of total 2008                              12
Nitrous oxide emissions Agricultural % of total 2008                                       12
Other greenhouse gas emissions  thousand metric tons of carbon dioxide equivalent 2012    167
Other greenhouse gas emissions  % change 1990-2012                                         53
dtype: int64